INSERT INTO Employee (firstname, lastname) VALUES
    ('Emmaline', 'MacKeller'),
    ('Starlin', 'Critchley'),
    ('Nicolea', 'Fillis'),
    ('Fredek', 'Ferreira'),
    ('Alyosha', 'Traynor'),
    ('Tabbitha', 'Holbury'),
    ('Brianna', 'Cadany'),
    ('Ediva', 'Bernardoni'),
    ('Aurore', 'Coyte'),
    ('Rusty', 'Grumell'),
    ('Ives', 'Clues'),
    ('Freeland', 'Hugenin'),
    ('Emmalynne', 'Coles'),
    ('Darren', 'Wanne'),
    ('Pauly', 'Bartalucci'),
    ('Alvira', 'Delacourt'),
    ('Clarine', 'Ledrane'),
    ('Peterus', 'Arkil'),
    ('Carolin', 'Wordsworth'),
    ('Elizabet', 'Vercruysse'),
    ('Zeke', 'Devonish'),
    ('Sigismond', 'Rendle'),
    ('Desmund', 'Victoria'),
    ('Irvine', 'Blakeslee'),
    ('Datha', 'Lorentz'),
    ('Ford', 'Edinburough'),
    ('Lacie', 'Rewbottom'),
    ('Nadine', 'Falloon'),
    ('Glyn', 'Storks'),
    ('Humbert', 'Pittam');

INSERT INTO Role (description, can_create, can_withdrawal) VALUES
    ('Admin Account', true, true),
    ('Doctor Account', true, false),
    ('Nurse', false, true);

INSERT INTO employee (firstname, lastname) VALUES

insert into account (password, role_id, employee_id) VALUES
    ('J6Z72KEkbeQh', 3, 1),
    ('2KN64vwdKt4s', 2, 2),
    ('EICGOCy', 2, 3),
    ('oHibDbC', 3, 4),
    ('CjYVhi', 3, 5),
    ('C17vd3cQ0', 3, 6),
    ('rlO0bY3tXWe', 3, 7),
    ('0PlK8X', 3, 8),
    ('TRlQjzwwYCeb', 2, 9),
    ('iUjUCZW', 2, 10),
    ('YqJXcktW', 1, 11),
    ('PbMsIDUhg', 2, 12),
    ('5pqFH6u', 2, 13),
    ('eXDz32G3', 3, 14),
    ('3sP4XPIaaNrg', 2, 15),
    ('sAeaknWYrX9h', 2, 16),
    ('E6oMGb1Fvfc7', 1, 17),
    ('F544zSfaUM', 2, 18),
    ('fDolmhS', 1, 19),
    ('zvVmOibVj', 3, 20),
    ('aHyBg4uQ2u9', 3, 21),
    ('JrRFn1sW7', 1, 22),
    ('8nUeMQVmeaAX', 2, 23),
    ('KCZPGOdrpJN', 1, 24),
    ('EVmcNuWe', 1, 25),
    ('IFKzOzyWgLb', 1, 26),
    ('NiOmIo1ceIq', 2, 27),
    ('JhYOpV', 3, 28),
    ('yxsEpqp9aE', 3, 29),
    ('LULo7kM0k', 2, 30);
